### ISSUE TITLE
Unfree license

### ISSUE THREAD

**Issue by nemobis** [3rd-ways-for-EU-exposure-notification/project-DESIRE#4]
Why NC license? Do you plan to sell copies of the specification?
https://meta.wikimedia.org/wiki/Free_knowledge_based_on_Creative_Commons_licenses

**Comment by vincent-grenoble** [comment]
Thank you so much @nemobis, we were not aware of such side-effects of the NC module (the wikimedia doc you've shared is enlightening). We've just updated the licence for CC BY-SA (and do the same for ROBERT). I therefore close this issue. 

Once again thank you for pointing this topic.

**Comment by nemobis** [comment]
Vincent Roca @ Inria, 12/05/20 12:17:
> Once again thank you for pointing this topic.

You're welcome! Thanks.
